spring.application.name=RatingService

server.port=8083


spring.data.mongodb.uri=mongodb://localhost:27017/microservices
spring.data.mongodb.auto-index-creation=true

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable registration with Eureka
eureka.client.register-with-eureka=true

# Enable fetching registry (to discover other services)
eureka.client.fetch-registry=true