spring.application.name=serviceRegistry

server.port=8761

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# eureka.instance.hostname=localhost
# It is the address other services should use to reach this service.

# eureka.client.register-with-eureka=false
# The Eureka Server is the registry, the master list of all services.
# Its job is to hold the list of services that register with it.
# Other services never need to call the server as a client(the caller service),
# so there is no reason for the server to register itself.

# eureka.client.fetch-registry=false
# Eureka server always knows about all registered services, because
# services register themselves with the server.
# But the server itself does not need to fetch the registry to know who are the
# registered services because it already knows.