spring.application.name=HotelService

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/HotelService?createTableIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Suraj@123
spring.jpa.hibernate.ddl-auto=update