spring.application.name=HotelService

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/HotelService
spring.datasource.username=root
spring.datasource.password=Suraj@123
spring.jpa.hibernate.ddl-auto=update


# spring - everything related to Spring Boot itself
# datasource - the part of Spring that manages database connections
# .url / .username / .password - specific properties under datasource category
# DataSource = an object that manages database connections

# spring.datasource.url
# Telling SpringBoot where your database is.
# Spring Boot will automatically use this URL to create a DataSource.

# jdbc:mysql://
# jdbc - Java Database Connectivity, the standard API for connecting Java to a database
# mysql - specifies the type of database (MySQL in this case)
# Together: Use JDBC to connect to a MySQL database.

# localhost:3306
# localhost - The database is running on your local machine
# 3306- Default MySQL port

# So Spring knows which machine and port to connect to.

# HotelService
# This is the database name you want to connect to
# You must create this database in MySQL first.

# JDBC vs DataSource

# JDBC
# Low-level API to connect to a database.
# You write code manually to open/close connections.

# Problems:
# Every time you need a connection, you repeat code
# No connection pooling (inefficient for multiple requests)
# Harder to integrate with frameworks

# DataSource
# Higher-level abstraction over JDBC, built on top of JDBC
# Manages database connections for you.
# Can include connection pooling, retries, and configuration.
# Spring Boot uses spring.datasource.* to automatically create a DataSource.


# spring.jpa.hibernate.ddl-auto=update
# spring - To set Spring Boot configuration
# jpa - Settings related to JPA (Java Persistence API)
# hibernate - Hibernate-specific settings (Hibernate is a JPA implementation)
# ddl-auto = tells Hibernate what to do automatically with the table when the app starts.

# none	      Does nothing. Safe for production if DB is managed manually. Tables must exist already
# validate	  Checks if DB schema matches your entities. Ensures consistency without changing anything. Throws error if mismatched, no table creation
# update	      Automatically creates missing tables/columns. Preserves existing data.
# create	      Drops existing tables and creates new ones. Quick for testing. Ensures clean schema. Deletes all existing data
# create-drop  Same as create, but drops tables on app shutdown. Useful for temporary/test databases. Deletes all data on shutdown. Not for production


# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable registration with Eureka
eureka.client.register-with-eureka=true

# Enable fetching registry (to discover other services)
eureka.client.fetch-registry=true